$schema: vscode://schemas/color-theme
author: Siamak Mokhtari, Modified by Lukas Wirth
name: Panda Syntax – Beta
colorSpaceName: sRGB
semanticClass: theme.dark.mu_panda
tokenColors:

# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------
# Generic <comment> matches
- scope: comment
  settings:
    foreground: _light-midnight
    fontStyle: italic

- scope: comment.block
  settings:
    foreground: _light-midnight
    fontStyle: italic

# -----------------------------------------------------------------------------
# Keywords & Operators
# -----------------------------------------------------------------------------
# Generic <keyword> matches
- scope: keyword
  settings:
    foreground: _keyword

# Make operators light gray by default
- scope: keyword.operator
  settings:
    foreground: _operator

# 1. Control flow operators
# 2. `new` keyword
- scope: keyword.control, keyword.operator.new
  settings:
    foreground: _keyword

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
# Generic <storage> matches
- scope: storage, storage.type
  settings:
    foreground: _keyword

- scope: storage.modifier
  settings:
    foreground: _keyword

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------
# Generic <constant> matches
- scope: constant
  settings:
    foreground: _type

# true/false booleans, null, undefined
- scope: constant.language
  settings:
    foreground: _light-pink

# Regex, string escape `\`
- scope: constant.character.escape
  settings:
    foreground: _light-green

# -----------------------------------------------------------------------------
# Variables && Parameters
# -----------------------------------------------------------------------------
# Generic <variable> matches
- scope: variable
  settings:
    foreground: _variable

# Function parameters
- scope: variable.parameter
  settings:
    foreground: _variable-light-gray

- scope: variable.other.constant, variable.language.this, variable.language.self
  settings:
    foreground: _light-pink

# -----------------------------------------------------------------------------
# Strings
# -----------------------------------------------------------------------------
# Generic string match
- scope: string
  settings:
    foreground: _string

# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
# Function names
- scope: entity.name.function
  settings:
    foreground: _function
- scope: entity.name.type
  settings:
    foreground: _type