name: vsce
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Cache vsce module
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install vsce
      run: npm install -g vsce
    - name: Install deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Build theme
      run: /home/runner/.deno/bin/deno run --allow-read --allow-write build.ts
    - name: Package extension
      run: vsce package
    - uses: actions/upload-artifact@v2
      with:
        name: Extension
        path: theme-mupanda-0.1.0.vsix
